//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_MessageManagements
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> SubordinateActivitiesID { get; set; }
        public string MessageName { get; set; }
        public string MessageConent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public System.Guid UserId { get; set; }
    }
}
