//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Activitys
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public Nullable<System.Guid> ActityType { get; set; }
        public Nullable<System.Guid> ActityState { get; set; }
        public string Imgurl { get; set; }
        public string Conent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public bool IsTop { get; set; }
        public string Longitude { get; set; }
        public string Dimension { get; set; }
    }
}
