//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CupcakeEntities : DbContext
    {
        public CupcakeEntities()
            : base("name=CupcakeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Activity_Activitys> Activity_Activitys { get; set; }
        public virtual DbSet<Activity_MessageManagements> Activity_MessageManagements { get; set; }
        public virtual DbSet<Activity_RegistrationStatus> Activity_RegistrationStatus { get; set; }
        public virtual DbSet<CustomPermissions> CustomPermissions { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
        public virtual DbSet<HasMedias> HasMedias { get; set; }
        public virtual DbSet<HasMenus> HasMenus { get; set; }
        public virtual DbSet<HasPermissions> HasPermissions { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Medias> Medias { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<News_News> News_News { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Questionnaire_QuestionnaireProblem> Questionnaire_QuestionnaireProblem { get; set; }
        public virtual DbSet<Questionnaire_QuestionResult> Questionnaire_QuestionResult { get; set; }
        public virtual DbSet<Questionnaire_QuestionStatistic> Questionnaire_QuestionStatistic { get; set; }
        public virtual DbSet<Questionnaire_QuestionSurvey> Questionnaire_QuestionSurvey { get; set; }
        public virtual DbSet<QuestionnaireProblemConditions> QuestionnaireProblemConditions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SysSetForm> SysSetForm { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Variables> Variables { get; set; }
        public virtual DbSet<Activity_ActivityStyle> Activity_ActivityStyle { get; set; }
        public virtual DbSet<SystemMessageInfo1> SystemMessageInfo1Set { get; set; }
        public virtual DbSet<TaskModule_TaskDisposal1> TaskModule_TaskDisposal1Set { get; set; }
        public virtual DbSet<TaskModule_TaskIssued1> TaskModule_TaskIssued1Set { get; set; }
        public virtual DbSet<Template_News1> Template_News1Set { get; set; }
        public virtual DbSet<WorkNotice_WorkNotices1> WorkNotice_WorkNotices1Set { get; set; }
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<CalendarAndScheduling_Table> CalendarAndScheduling_Table { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Comments_Collect> Comments_Collect { get; set; }
        public virtual DbSet<Comments_Praise> Comments_Praise { get; set; }
        public virtual DbSet<MapPoint_Map> MapPoint_Map { get; set; }
        public virtual DbSet<MapPoint_MapPoint> MapPoint_MapPoint { get; set; }
    }
}
