//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members_Members
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserRealName { get; set; }
        public string Tel { get; set; }
        public System.Guid UserType { get; set; }
        public string Email { get; set; }
        public System.Guid Status { get; set; }
        public string TempPwd { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int LoginCount { get; set; }
        public string LastLoginIP { get; set; }
        public string ImageUrl { get; set; }
        public string ValidCode { get; set; }
        public bool Remember { get; set; }
        public int failLoginCount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
