//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireProblemConditions
    {
        public QuestionnaireProblemConditions()
        {
            this.Questionnaire_QuestionnaireProblem = new HashSet<Questionnaire_QuestionnaireProblem>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public System.Guid QuestionSurveyId { get; set; }
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Questionnaire_QuestionnaireProblem> Questionnaire_QuestionnaireProblem { get; set; }
    }
}
