//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire_QuestionStatistic
    {
        public System.Guid Id { get; set; }
        public System.Guid QuestionSurveyId { get; set; }
        public System.Guid QuestionInfoId { get; set; }
        public System.Guid QuestionResultId { get; set; }
        public System.Guid QuestionType { get; set; }
        public string Result { get; set; }
        public int Uid { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
