//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModule_TaskIssued1
    {
        public System.Guid Id { get; set; }
        public string TaskOverview { get; set; }
        public string Description { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string TaskType { get; set; }
        public System.DateTime CompleteDate { get; set; }
        public string EnclosureName { get; set; }
        public string EnclosureUrl { get; set; }
        public string Thumbnail { get; set; }
        public string Department { get; set; }
        public bool TaskManagement { get; set; }
        public string Publisher { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
