//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cupcake.Web.WapTemplate.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModule_TaskDisposal1
    {
        public System.Guid Id { get; set; }
        public System.Guid TaskIssuedId { get; set; }
        public System.DateTime DisposalCompletedDate { get; set; }
        public string DisposalResult { get; set; }
        public string EnclosureName { get; set; }
        public string EnclosureUrl { get; set; }
        public string Thumbnail { get; set; }
        public string DisposalPerson { get; set; }
        public System.DateTime EventDisposalDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
    }
}
